### ISSUE TITLE
Crashing Game, Crash Report Included

### ISSUE THREAD

**Issue by DJMan255** [DrunkBlood/Lucky-Ore#2]
---- Minecraft Crash Report ----
// There are four lights!

Time: 10/12/21, 2:32 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fmllegacy.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.17.1-37.0.84-universal.jar%2393!:?] {re:classloading}
	at net.minecraftforge.fmlclient.ClientModLoader.completeModLoading(ClientModLoader.java:185) ~[forge-1.17.1-37.0.84-universal.jar%2393!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,pl:accesstransformer:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:507) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,pl:accesstransformer:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1248) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,xf:OptiFine:default,pl:accesstransformer:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,pl:accesstransformer:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,pl:accesstransformer:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2389!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.84.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Class.getDeclaredField(Class.java:2549) ~[?:?] {}
-- MOD luckyore --
Details:
	Caused by 0: net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: features
		at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:241) ~[fmlcore-1.17.1-37.0.84.jar%2390!:?] {}
		at net.minecraftforge.fml.util.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:119) ~[fmlcore-1.17.1-37.0.84.jar%2390!:?] {}
		at drunkblood.luckyore.world.gen.ModOres.addFeatureToBiome(ModOres.java:90) ~[luckyore-1.0.1-1.17.1.jar%2376!:1.0.1-1.17.1] {re:classloading}
		at drunkblood.luckyore.world.gen.ModOres.setupOres(ModOres.java:66) ~[luckyore-1.0.1-1.17.1.jar%2376!:1.0.1-1.17.1] {re:classloading}
		at drunkblood.luckyore.events.ModEventSubscriber.CommonSetup(ModEventSubscriber.java:63) ~[luckyore-1.0.1-1.17.1.jar%2376!:1.0.1-1.17.1] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_69_ModEventSubscriber_CommonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.84.jar%2391!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.84.jar%2390!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: luckyore-1.0.1-1.17.1.jar
	Failure message: Lucky Ore (luckyore) encountered an error during the common_setup event phase
		net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: features
	Mod Version: 1.0.0-1.17.1
	Mod Issue URL: https://github.com/DrunkBlood/Lucky-Ore/issues
	Exception message: java.lang.NoSuchFieldException: features
Stacktrace:
	at java.lang.Class.getDeclaredField(Class.java:2549) ~[?:?] {}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:235) ~[fmlcore-1.17.1-37.0.84.jar%2390!:?] {}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:119) ~[fmlcore-1.17.1-37.0.84.jar%2390!:?] {}
	at drunkblood.luckyore.world.gen.ModOres.addFeatureToBiome(ModOres.java:90) ~[luckyore-1.0.1-1.17.1.jar%2376!:1.0.1-1.17.1] {re:classloading}
	at drunkblood.luckyore.world.gen.ModOres.setupOres(ModOres.java:66) ~[luckyore-1.0.1-1.17.1.jar%2376!:1.0.1-1.17.1] {re:classloading}
	at drunkblood.luckyore.events.ModEventSubscriber.CommonSetup(ModEventSubscriber.java:63) ~[luckyore-1.0.1-1.17.1.jar%2376!:1.0.1-1.17.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_69_ModEventSubscriber_CommonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.84.jar%2391!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.84.jar%2390!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 536269440 bytes (511 MiB) / 2048917504 bytes (1954 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18752.55
	Virtual memory used (MB): 13279.21
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 29.23
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	OptiFine Version: OptiFine_1.17.1_HD_U_H1_pre6
	OptiFine Build: 20211008-115759
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 optiforge TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
		 FakeOptiFine TRANSFORMATIONSERVICE 
		 optiforgewrapper TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		torchslabmod-1.17.1_v1.7.1.jar                    |Torch Slab Mod                |torchslabmod                  |1.7.1               |SIDED_SETU|Manifest: NOSIGNATURE
		BiomesOPlenty-1.17.1-14.0.0.36-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.36    |SIDED_SETU|Manifest: NOSIGNATURE
		SimpleCoreLib-1.17.1-3.0.4.0.jar                  |SimpleCoreLib                 |simplecorelib                 |1.17.1-3.0.4.0      |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-fences-1.0.1-mc1.17.1.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.17.1-8.1.0.26.jar                           |Just Enough Items             |jei                           |8.1.0.26            |SIDED_SETU|Manifest: NOSIGNATURE
		wthit-forge-3.9.3.jar                             |wthit                         |wthit                         |3.9.3               |SIDED_SETU|Manifest: NOSIGNATURE
		torohealth-1.17.1-forge-1.jar                     |ToroHealth                    |torohealth                    |1.17.1-forge-1      |SIDED_SETU|Manifest: NOSIGNATURE
		paintings-1.17.1-8.0.0.1.jar                      |Paintings ++                  |paintings                     |1.17.1-8.0.0.1      |SIDED_SETU|Manifest: NOSIGNATURE
		Xaeros_Minimap_21.17.2_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |21.17.2             |SIDED_SETU|Manifest: NOSIGNATURE
		goldenhopper-1.2.4-1.17.1.jar                     |Golden Hopper                 |goldenhopper                  |1.2.4               |SIDED_SETU|Manifest: NOSIGNATURE
		advancednetherite-1.8.2-1.17.1.jar                |Advanced Netherite            |advancednetherite             |1.8.2               |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.9.3-1.17.1.jar                          |Citadel                       |citadel                       |1.9.3               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.13.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.13.0              |SIDED_SETU|Manifest: NOSIGNATURE
		NaturesCompass-1.17.1-1.9.2-forge.jar             |Nature's Compass              |naturescompass                |1.17.1-1.9.2-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		EarthMobs-1.17.1-0.3.1.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.17.1-0.3.1        |SIDED_SETU|Manifest: NOSIGNATURE
		InventoryHud_[1.17.1].forge-3.4.0.jar             |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.0               |SIDED_SETU|Manifest: NOSIGNATURE
		coppermod-forge-1.0.jar                           |Copper Armor & Tools          |copperarmorandtools           |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		DungeonCrawl-1.17.1-2.3.2.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.2               |SIDED_SETU|Manifest: NOSIGNATURE
		ExplorersCompass-1.17.1-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.17.1-1.1.2-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		cfm-7.0.0pre25-1.17.1.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre25         |SIDED_SETU|Manifest: NOSIGNATURE
		potionbundles-1.17.1-1.1.jar                      |Potion Bundles                |potionbundles                 |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		Enhanced-Farming-1.17.1-1.2.2.jar                 |Enhanced Farming              |enhancedfarming               |1.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
		DisplayCase-1.17.1-0.2.jar                        |DisplayCase Mod               |display_case                  |1.17.1-0.1          |SIDED_SETU|Manifest: NOSIGNATURE
		FallingTree-1.17.1-2.14.2.jar                     |FallingTree                   |fallingtree                   |2.14.2              |SIDED_SETU|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		restored_earth-1.17.1-1.0.0.jar                   |Restored Earth                |restored_earth                |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.17.1-37.0.84-universal.jar                |Forge                         |forge                         |37.0.84             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.17.1-2.1.0.jar                |AppleSkin                     |appleskin                     |2.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Aquaculture-1.17.1-2.2.2.jar                      |Aquaculture 2                 |aquaculture                   |1.17.1-2.2.2        |SIDED_SETU|Manifest: NOSIGNATURE
		GameMenuModOption-1.17.1-Forge-1.9.jar            |Game Menu Mod Option          |gamemenumodoption             |1.9                 |SIDED_SETU|Manifest: NOSIGNATURE
		veinmining-forge-1.17.1-0.12.jar                  |Vein Mining                   |veinmining                    |1.17.1-0.12         |SIDED_SETU|Manifest: NOSIGNATURE
		durabilitytooltip-1.0.0-mc1.17.jar                |durabilitytooltip             |durabilitytooltip             |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		SimpleOres2-1.17.1-3.0.1.4.jar                    |Simple Ores                   |simpleores                    |1.17.1-3.0.1.4      |SIDED_SETU|Manifest: NOSIGNATURE
		ironchest-1.17.1-12.0.2.jar                       |Iron Chests                   |ironchest                     |1.17.1-12.0.2       |SIDED_SETU|Manifest: NOSIGNATURE
		corpse-1.17.1-1.0.4.jar                           |Corpse                        |corpse                        |1.17.1-1.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
		luckyore-1.0.1-1.17.1.jar                         |Lucky Ore                     |luckyore                      |1.0.0-1.17.1        |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 4d673d31-3d78-427f-85ea-2e4754ce3d7e
	FML: 37.0
	Forge: net.minecraftforge:37.0.84

**Comment by DrunkBlood** [comment]
I rewote the ore gen. Try the new version 1.1.1-1.17.1
